#ifndef a63pwrfix_self_hold_kl15_strategy_H__
#define a63pwrfix_self_hold_kl15_strategy_H__

extern const unsigned char a63pwrfix_self_hold_kl15_strategy[];
#define a63pwrfix_self_hold_kl15_strategy_CODE_LENGTH 980U
#define a63pwrfix_self_hold_kl15_strategy_CODE_CRC 0X2EE85E0UL

#endif
