#ifndef a64pwrfix_self_return_kl15_strategy_H__
#define a64pwrfix_self_return_kl15_strategy_H__

extern const unsigned char a64pwrfix_self_return_kl15_strategy[];
#define a64pwrfix_self_return_kl15_strategy_CODE_LENGTH 644U
#define a64pwrfix_self_return_kl15_strategy_CODE_CRC 0XD9C7C4E2UL
#endif
